lch_media_image_add:
    path: /image/add
    defaults: { _controller: LchMediaBundle:Image:add }
    methods:  [ PUT, POST ]
    options:
        expose: true

lch_media_image_list:
    path: /image/list
    defaults: { _controller: LchMediaBundle:Image:list }
    methods:  [ GET ]
    options:
        expose: true