lch_media_list:
    path: /list/{type}
    defaults: { _controller: LchMediaBundle:Media:list, type: "all" }
    methods:  [ GET ]
    options:
        expose: true

lch_media_add:
    path: /add/{type}
    defaults: { _controller: LchMediaBundle:Media:add }
    methods:  [ PUT, POST ]
    options:
        expose: true

#lch_media_image_add:
#    path: /image/add
#    defaults: { _controller: LchMediaBundle:Image:add }
#    methods:  [ PUT, POST ]
#    options:
#        expose: true

