services:
    lch.media_bundle.media_uploader:
        class: Lch\MediaBundle\Uploader\MediaUploader
        arguments: [ '%kernel.root_dir%', '%lch_media.root_folder%' ]

    lch.media_bundle.addmedia:
        class: Lch\MediaBundle\Form\AddOrChooseImageType
        arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher" ]
        tags:
            - { name: form.type }

    lch_image_validator:
        class: Lch\MediaBundle\Validator\Constraints\ImageExtensionValidator
        arguments: [ '%kernel.root_dir%' ]
        tags:
            - { name: validator.constraint_validator, alias: alias_name }

    lch.media_bundle.media_manager:
        class: Lch\MediaBundle\Manager\MediaManager
        arguments: [ '@lch.media_bundle.media_uploader' ]

    lch.media_bundle.image_extension:
        class: Lch\MediaBundle\Twig\Extension\ImageExtension
        tags:
          - { name: twig.extension }

    lch.media_bundle.media_type_finder:
        class: MediaTypeFinder