parameters:
  lch.media.types:
    image:
      entity:     'Lch\MediaBundle\Entity\Image'
      form:       'Lch\MediaBundle\Form\ImageType'
      add_view:   'LchMediaBundle:Image/fragments:add.html.twig'
      thumbnail_view: 'LchMediaBundle:Image/fragments:thumbnail.html.twig'
      list_item_view: 'LchMediaBundle:Image/fragments:list.item.html.twig'
      extensions: ['jpg', 'jpeg', 'png', 'gif']

    pdf:
      entity:     'Lch\MediaBundle\Entity\Pdf'
      form:       'Lch\MediaBundle\Form\PdfType'
      add_view:   'LchMediaBundle:Pdf/fragments:add.html.twig'
      thumbnail_view: 'LchMediaBundle:Pdf/fragments:thumbnail.html.twig'
      list_item_view: 'LchMediaBundle:Pdf/fragments:list.item.html.twig'
      extensions: ['pdf']


services:
  lch.media.uploader:
    class: Lch\MediaBundle\Uploader\MediaUploader
    arguments: [ '%kernel.root_dir%', '%lch_media.root_folder%' ]
    lazy: true

  lch.media.form:
    class: Lch\MediaBundle\Form\AddOrChooseMediaType
    arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher", '%lch.media.types%' ]
    tags:
      - { name: form.type }

  lch.media.manager:
    class: Lch\MediaBundle\Manager\MediaManager
    arguments: [ '@lch.media.uploader', '@doctrine.orm.entity_manager', '@event_dispatcher', '%lch.media.types%' ]
    lazy: true

  lch.media.extension.validator:
    class: Lch\MediaBundle\Validator\Constraints\HasAllowedFileExtensionValidator
    arguments: [ '%kernel.root_dir%', '%lch.media.types%' ]
    tags:
      - { name: validator.constraint_validator, alias: alias_name }

  lch.media.twig.extension:
    class: Lch\MediaBundle\Twig\Extension\MediaExtension
    arguments: [ '@lch.media.manager', '@twig', '%lch.media.types%' ]
    tags:
      - { name: twig.extension }
    lazy: true

  lch.media.image.subscriber:
    class: Lch\MediaBundle\Listener\ImageSubscriber
    arguments: ['@lch.media.manager']
    tags:
      - { name: kernel.event_subscriber }
    lazy: true

  lch.media.pdf.subscriber:
    class: Lch\MediaBundle\Listener\PdfSubscriber
    arguments: ['@lch.media.manager']
    tags:
      - { name: kernel.event_subscriber }
    lazy: true