parameters:
  lch.media.types:
    image:
      entity: 'Lch\MediaBundle\Entity\Image'
      form:   'Lch\MediaBundle\Form\ImageType'
      extensions: ['jpg', 'png', 'gif']

    pdf:
      entity: 'Lch\MediaBundle\Entity\Pdf'
      form:   'Lch\MediaBundle\Form\PdfType'
      extensions: ['pdf']


services:
  lch.media.uploader:
    class: Lch\MediaBundle\Uploader\MediaUploader
    arguments: [ '%kernel.root_dir%', '%lch_media.root_folder%' ]

  lch.media.form:
    class: Lch\MediaBundle\Form\AddOrChooseMediaType
    arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher", '%lch.media.types%' ]
    tags:
      - { name: form.type }

  lch.media.manager:
    class: Lch\MediaBundle\Manager\MediaManager
    arguments: [ '@lch.media.uploader', '@doctrine.orm.entity_manager' ]

  lch.media.image.validator:
    class: Lch\MediaBundle\Validator\Constraints\ImageExtensionValidator
    arguments: [ '%kernel.root_dir%' ]
    tags:
      - { name: validator.constraint_validator, alias: alias_name }

  lch.media.image.extension:
    class: Lch\MediaBundle\Twig\Extension\ImageExtension
    tags:
      - { name: twig.extension }

  lch.media.image.pre_persist.listener:
    class: Lch\MediaBundle\Listener\ImagePrePersistListener
    arguments: ['@lch.media.manager']
    tags:
      - { name: kernel.event_listener, event: lch.media.pre_persist, method: onImagePrePersist }
#    lazy: true